name: "EncGINE"

init:
  _target_: src.models.gin_encoded.EncodedGINE
  _recursive_: false
  
  
  num_tasks: 12           
  embedding_dim: 256      
  hidden_channels: 256   
  
  
  encoder_num_heads: 4     # 256 / 4 = 64 dim per head
  encoder_dropout: 0.1    
  
  
  num_gnn_layers: 4        
  gnn_mlp_layers: 2        
  readout_mlp_layers: 2    
  
  
  dropout: 0.5             
  activation: "relu"       
  pooling_type: "mean"    
  use_residual: true      
  learn_eps: true         




