# configs/model/gine.yaml

name: "EncGINE"

init:
  _target_: src.models.gin_encoded.EncodedGINE
  _recursive_: false
  embedding_dim: 256
  hidden_channels: 256
  num_layers: 4
  dropout: 0.5


  # embedding_dim: int = 256,
  # hidden_channels: int = 256,
  # num_tasks: int = 12,
  # num_layers: int = 4,
  # dropout: float = 0.5,



