# configs/model/gin_deep.yaml

name: "GNN"

init:
  _target_: src.models.gnn.GNN
  # _recursive_: false
 
  num_layer: 5
  emb_dim: 300
  gnn_type: "gin"
  virtual_node: true
  residual: false
  drop_ratio: 0.5
  JK: "last"
  graph_pooling: "mean"
