_wandb:
    value:
        cli_version: 0.22.3
        e:
            n1hqxko2c3jyg65b4m8ntcx9tqbrx94y:
                cpu_count: 24
                cpu_count_logical: 24
                disk:
                    /:
                        total: "76817485824"
                        used: "6318854144"
                email: santos.osorio.afonso@gmail.com
                executable: /zhome/fd/3/223554/miniconda3/envs/deep_learning/bin/python
                git:
                    commit: cc5de9e3ee38562105d670ce9e7f83303f68514b
                    remote: https://github.com/pablorocg/semi-supervised-gnn-drug-discovery.git
                host: n-62-31-13
                memory:
                    total: "404874944512"
                os: Linux-6.1.154-1.el9.elrepo.x86_64-x86_64-with-glibc2.34
                program: -m src.lightning_modules.mean_teacher
                python: CPython 3.12.12
                root: .
                startedAt: "2025-11-11T10:39:41.209024Z"
                writerId: n1hqxko2c3jyg65b4m8ntcx9tqbrx94y
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 9
                - 77
                - 103
            "2":
                - 1
                - 9
                - 77
                - 103
            "3":
                - 7
                - 13
                - 66
            "4": 3.12.12
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
compile_mode:
    value: null
cosine_period_ratio:
    value: 1
ema_decay:
    value: 0.999
lambda_consistency:
    value: 1
learning_rate:
    value: 0.001
momentum:
    value: 0.99
nesterov:
    value: true
num_classes:
    value: 1
test_transforms:
    value: null
train_transforms:
    value: null
val_transforms:
    value: null
warmup_epochs:
    value: 5
weight_decay:
    value: 3e-05
weights:
    value: null
