# configs/dataset/qm9.yaml

name: QM9

init:
  _target_: src.data.qm9.QM9DataModule
  target: null  # Use null for all targets or specify a target index (0-12)
  batch_size_train: 32
  batch_size_inference: 64
  num_workers: 4
  splits: [0.72, 0.08, 0.1, 0.1]
  seed: 42
  subset_size: null  
  data_augmentation: false
  name: qm9

  



