# configs/logger/wandb.yaml

wandb:
  _target_: pytorch_lightning.loggers.WandbLogger
  project_name: "molecule-property-prediction"
  run_name: "${dataset.name}_${model.name}_${now:%Y-%m-%d_%H-%M-%S}"
  save_dir: "${oc.env.LOGS_DIR}"
  offline: false
  log_model: false
  tags: 
    - "${dataset.name}"
    - "${model.name}"
  notes: "Experiment with ${dataset.name} dataset"