# configs/logger/wandb.yaml

wandb:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: "${dataset.name}_${model.name}_${now:%Y-%m-%d_%H-%M-%S}"  
  project: "molecule-property-prediction"  
  save_dir: "${oc.env:LOGS_DIR,./logs}" 
  offline: false
  log_model: false
  tags:  
    - "${dataset.name}"
    - "${model.name}"
  notes: "Experiment with ${dataset.name} dataset"  



